version: '3'

services:
  quantum_ml:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount for development to see changes without rebuilding
      - ./:/app
    # Interactive mode
    stdin_open: true
    tty: true